services:
  backend_pyton:
    build:
      context: ./backend_pyton
      dockerfile: Dockerfile
    container_name: gis-backend-python
    restart: unless-stopped
    env_file:
      - ./backend_pyton/.env
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - global-network

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: gis-api-node
    restart: unless-stopped
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./gis-dashboard/datas:/gis-dashboard/datas:ro
    networks:
      - global-network

  gis-dashboard:
    build:
      context: ./gis-dashboard
      dockerfile: Dockerfile
    container_name: gis-dashboard-nuxt
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - api
      - backend_pyton
    networks:
      - global-network

networks:
  global-network:
    external: true
