services:
  backend_fastapi:
    build:
      context: ./backend_fastapi
      dockerfile: Dockerfile
    container_name: gis-backend-python
    restart: unless-stopped
    env_file:
      - path: ./backend_fastapi/.env
        required: false
    ports:
      - "127.0.0.1:8000:8000"

  gis-dashboard:
    build:
      context: ./gis-dashboard
      dockerfile: Dockerfile
    container_name: gis-dashboard-nuxt
    restart: unless-stopped
    env_file:
      - path: ./gis-dashboard/.env
        required: false
    environment:
      NUXT_API_BASE_URL_PYTHON_SERVER: http://gis-backend-python:8000/api
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend_fastapi
