services:
  backend_fastapi:
    build:
      context: ./backend_fastapi
      dockerfile: Dockerfile
    container_name: gis-backend-python
    restart: unless-stopped
    network_mode: host
    env_file:
      - path: ./backend_fastapi/.env
        required: false
    command: ["uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", "8000"]

  gis-dashboard:
    build:
      context: ./gis-dashboard
      dockerfile: Dockerfile
    container_name: gis-dashboard-nuxt
    restart: unless-stopped
    network_mode: host
    env_file:
      - path: ./gis-dashboard/.env
        required: false
    environment:
      NUXT_API_BASE_URL_PYTHON_SERVER: http://127.0.0.1:8000/api
    command: ["npm", "run", "dev", "--", "--host", "127.0.0.1", "--port", "3000"]
    depends_on:
      - backend_fastapi
