"""baseline_relational_schema

Revision ID: 1300c10f7cda
Revises: 
Create Date: 2026-07-01 14:05:58.353321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1300c10f7cda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_area', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_area')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('estates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('kode_est', sa.String(length=50), nullable=False),
    sa.Column('nama_estate', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_est')
    )
    op.create_index(op.f('ix_estates_id'), 'estates', ['id'], unique=False)
    op.create_table('afdelings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estate_id', sa.Integer(), nullable=False),
    sa.Column('kode_afd', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_afdelings_id'), 'afdelings', ['id'], unique=False)
    op.create_table('bloks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('afdeling_id', sa.Integer(), nullable=False),
    sa.Column('kode_blok', sa.String(length=50), nullable=False),
    sa.Column('nama_blok', sa.String(length=100), nullable=False),
    sa.Column('ownership', sa.String(length=50), nullable=True),
    sa.Column('tahun_tanam', sa.Integer(), nullable=True),
    sa.Column('bulan_tanam', sa.String(length=20), nullable=True),
    sa.Column('topografi', sa.String(length=50), nullable=True),
    sa.Column('jenis_tanah', sa.String(length=100), nullable=True),
    sa.Column('jenis_bibit', sa.String(length=100), nullable=True),
    sa.Column('status_tanaman', sa.String(length=20), nullable=True),
    sa.Column('luas_tanah', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('luas_tanam', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['afdeling_id'], ['afdelings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_bloks_geom', 'bloks', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_bloks_id'), 'bloks', ['id'], unique=False)
    op.create_index(op.f('ix_bloks_kode_blok'), 'bloks', ['kode_blok'], unique=True)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_bloks_kode_blok'), table_name='bloks')
    op.drop_index(op.f('ix_bloks_id'), table_name='bloks')
    # op.drop_index('idx_bloks_geom', table_name='bloks', postgresql_using='gist')
    op.drop_table('bloks')
    op.drop_index(op.f('ix_afdelings_id'), table_name='afdelings')
    op.drop_table('afdelings')
    op.drop_index(op.f('ix_estates_id'), table_name='estates')
    op.drop_table('estates')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
