"""add_table_pt

Revision ID: 631902561d20
Revises: 1300c10f7cda
Create Date: 2026-07-02 02:44:48.454569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631902561d20'
down_revision: Union[str, Sequence[str], None] = '1300c10f7cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_pt', sa.String(length=50), nullable=False),
    sa.Column('nama_pt', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pts_id'), 'pts', ['id'], unique=False)
    op.create_index(op.f('ix_pts_kode_pt'), 'pts', ['kode_pt'], unique=True)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.drop_index(op.f('ix_pts_kode_pt'), table_name='pts')
    op.drop_index(op.f('ix_pts_id'), table_name='pts')
    op.drop_table('pts')
    # ### end Alembic commands ###
